email:
  login: ""
  pass: ""
  smtpServerEndpoint: "smtp.mail.ru:587"
  smtpServerHost: "smtp.mail.ru"
httpServer:
  endpoint: "127.0.0.1:7100"
  writeTimeout: 15
  readTimeout: 15
apiKey: "r42RQr234VtEqeRVbt"
